name: Build on Tag

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.*'

      - name: Build in Node
        run: cd frontend; npm run build

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-verison: '1.18.*'

      - name: Copy build.zip to Go environment
        run: cp ./build.zip ../backend/;cd ../backend

      - name: Gen Golang static code
        run: go run main.go build

      - name: Go build windows amd64
        run: GOARCH=amd64 GOOS=windows go build main.go -o 电子礼金簿.windows.amd64.exe

      - name: Go build windows 386
        run: GOARCH=386 GOOS=windows go build main.go -o 电子礼金簿.windows.386.exe

      - name: Go build windows arm
        run: GOARCH=arm GOOS=windows go build main.go -o 电子礼金簿.windows.arm.exe

      - name: Go build windows arm64
        run: GOARCH=arm64 GOOS=windows go build main.go -o 电子礼金簿.windows.arm64.exe

      - name: Go build darwin arm64
        run: GOARCH=arm64 GOOS=darwin go build main.go -o 电子礼金簿.macos.arm64

      - name: Go build darwin amd64
        run: GOARCH=amd64 GOOS=darwin go build main.go -o 电子礼金簿.macos.amd64
        
      - name: Go build linux 386
        run: GOARCH=386 GOOS=linux go build main.go -o 电子礼金簿.linux.386
        
      - name: Go build linux amd64
        run: GOARCH=amd64 GOOS=linux go build main.go -o 电子礼金簿.linux.amd64
        
      - name: Go build linux arm
        run: GOARCH=arm GOOS=linux go build main.go -o 电子礼金簿.linux.arm
        
      - name: Go build linux arm64
        run: GOARCH=arm64 GOOS=linux go build main.go -o 电子礼金簿.linux.arm64

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset Windows 386
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: backend/电子礼金簿.windows.386.exe
            asset_name: 电子礼金簿.windows.386.exe

      - name: Upload Release Asset Windows amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: backend/电子礼金簿.windows.amd64.exe
            asset_name: 电子礼金簿.windows.amd64.exe

      - name: Upload Release Asset Windows arm
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: backend/电子礼金簿.windows.arm.exe
            asset_name: 电子礼金簿.windows.arm.exe

      - name: Upload Release Asset Windows arm64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: backend/电子礼金簿.windows.arm64.exe
            asset_name: 电子礼金簿.windows.arm64.exe

      - name: Upload Release Asset Mac arm64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: backend/电子礼金簿.mac.arm64.exe
            asset_name: 电子礼金簿.mac.arm64.exe

      - name: Upload Release Asset Mac amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: backend/电子礼金簿.mac.amd64.exe
            asset_name: 电子礼金簿.mac.amd64.exe