name: Build on Tag

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.*'

      - name: Build in Node
        run: cd frontend;npm install; npm run build

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-verison: '1.18.*'

      - name: Copy build.zip to Go environment
        run: cp frontend/build.zip backend/

      - name: Gen Golang static code
        run: cd backend;go run main build;

      - name: cd backend; go build windows amd64
        run: GOARCH=amd64 GOOS=windows cd backend; go build -o 电子礼金簿.windows.amd64.exe main.go

      - name: cd backend; go build windows 386
        run: GOARCH=386 GOOS=windows cd backend; go build -o 电子礼金簿.windows.386.exe main.go

      - name: cd backend; go build windows arm
        run: GOARCH=arm GOOS=windows cd backend; go build -o 电子礼金簿.windows.arm.exe main.go

      - name: cd backend; go build windows arm64
        run: GOARCH=arm64 GOOS=windows cd backend; go build -o 电子礼金簿.windows.arm64.exe main.go

      - name: cd backend; go build darwin arm64
        run: GOARCH=arm64 GOOS=darwin cd backend; go build -o 电子礼金簿.macos.arm64 main.go

      - name: cd backend; go build darwin amd64
        run: GOARCH=amd64 GOOS=darwin cd backend; go build -o 电子礼金簿.macos.amd64 main.go
        
      - name: cd backend; go build linux 386
        run: GOARCH=386 GOOS=linux cd backend; go build -o 电子礼金簿.linux.386 main.go
        
      - name: cd backend; go build linux amd64
        run: GOARCH=amd64 GOOS=linux cd backend; go build -o 电子礼金簿.linux.amd64 main.go
        
      - name: cd backend; go build linux arm
        run: GOARCH=arm GOOS=linux cd backend; go build -o 电子礼金簿.linux.arm main.go
        
      - name: cd backend; go build linux arm64
        run: GOARCH=arm64 GOOS=linux cd backend; go build -o 电子礼金簿.linux.arm64 main.go

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false


      - name: Release Upload
        uses: d1ceward/draft-assets-release-action@v2.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            backend/电子礼金簿.windows.386.exe
            backend/电子礼金簿.windows.amd64.exe
            backend/电子礼金簿.windows.arm.exe
            backend/电子礼金簿.windows.arm64.exe
